name: ballcom

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=63km6xou9Z8GeZ
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: unless-stopped
  
  customerservice:
    build:
      context: .
      dockerfile: CustomerService.Dockerfile
    container_name: customerservice
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "3001:3001"
