// <auto-generated />
using System;
using CustomerService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20240619083446_secondCreate")]
    partial class secondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b9c24d5-1f47-40ef-800b-09cfe8e5c89b"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "ICTutor",
                            FirstName = "Sybrand",
                            LastName = "Bos",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("1d11cc97-809b-45b1-b096-516140f71f93"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Willy's",
                            FirstName = "Tristan",
                            LastName = "Goossens",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("532cd2ef-1ed8-4624-b780-101e34d28a8e"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Dropshipper",
                            FirstName = "Thimo",
                            LastName = "Luijsterburg",
                            PhoneNumber = "0612345678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
