// <auto-generated />
using System;
using CustomerService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20240619081954_initCreate")]
    partial class initCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82b5a43e-0ab3-4ac7-9dc2-e9ed2b2d22d9"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "ICTutor",
                            FirstName = "Sybrand",
                            LastName = "Bos",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("78151e52-a564-460e-8d4d-7d58bcd49890"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Willy's",
                            FirstName = "Tristan",
                            LastName = "Goossens",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("ea043a64-8f06-41fb-9b54-b143d911bcfb"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Dropshipper",
                            FirstName = "Thimo",
                            LastName = "Luijsterburg",
                            PhoneNumber = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
