// <auto-generated />
using System;
using CustomerService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20240621075249_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d43c3429-dd30-4384-baba-6b2eb425bfca"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "ICTutor",
                            FirstName = "Sybrand",
                            LastName = "Bos",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("2cf9b7df-e7fd-461d-8697-500a13826406"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Willy's",
                            FirstName = "Tristan",
                            LastName = "Goossens",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("d1b96ae1-ec78-43b6-83b5-bce5359b2dc6"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Dropshipper",
                            FirstName = "Thimo",
                            LastName = "Luijsterburg",
                            PhoneNumber = "0612345678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
