// <auto-generated />
using System;
using CustomerService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerService.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7f53e2b-0e68-4dea-8b81-f636ad4c1e98"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "ICTutor",
                            FirstName = "Sybrand",
                            LastName = "Bos",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("b30226fe-cb36-451d-b28e-e1158cbea431"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Willy's",
                            FirstName = "Tristan",
                            LastName = "Goossens",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = new Guid("5e24d267-480e-4954-8654-0041f5f38f62"),
                            Address = "Avansstraat 123, 1234AB Breda",
                            CompanyName = "Dropshipper",
                            FirstName = "Thimo",
                            LastName = "Luijsterburg",
                            PhoneNumber = "0612345678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
