// <auto-generated />
using System;
using InventoryManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagement.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ada76f7-2ca0-476f-8a9a-73a8323a008c"),
                            Description = "Description 1",
                            Name = "Product 1",
                            Price = 10m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("2583abb5-89e7-49b4-b4d2-e5055e7eba8b"),
                            Description = "Description 2",
                            Name = "Product 2",
                            Price = 20m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("InventoryManagement.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("ProductEvents");

                    b.HasDiscriminator<string>("EventType").HasValue("Event");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagement.Events.ProductCreatedEvent", b =>
                {
                    b.HasBaseType("InventoryManagement.Events.Event");

                    b.HasDiscriminator().HasValue("ProductCreatedEvent");
                });

            modelBuilder.Entity("InventoryManagement.Events.ProductUpdatedEvent", b =>
                {
                    b.HasBaseType("InventoryManagement.Events.Event");

                    b.HasDiscriminator().HasValue("ProductUpdatedEvent");
                });

            modelBuilder.Entity("InventoryManagement.Events.StockDecreasedEvent", b =>
                {
                    b.HasBaseType("InventoryManagement.Events.Event");

                    b.HasDiscriminator().HasValue("StockDecreasedEvent");
                });

            modelBuilder.Entity("InventoryManagement.Events.StockIncreasedEvent", b =>
                {
                    b.HasBaseType("InventoryManagement.Events.Event");

                    b.HasDiscriminator().HasValue("StockIncreasedEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
